site_name: MetaMCP Documentation
site_description: Documentation for the MCP Meta-Server
site_author: MetaMCP Team
site_url: https://metamcp.org

repo_name: lichtbaer/MetaMCP
repo_url: https://github.com/lichtbaer/MetaMCP
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-wifi
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-wifi-off
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.download
    - navigation.instant.loading
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: lichtbaer
      repo: MetaMCP
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lichtbaer/MetaMCP
    - icon: fontawesome/brands/discord
      link: https://discord.gg/metamcp
  version:
    provider: mike

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Overview: user-guide/overview.md
    - Architecture: user-guide/architecture.md
    - API Reference: user-guide/api-reference.md
    - MCP Protocol: user-guide/mcp-protocol.md
    - Tool Management: user-guide/tool-management.md
    - Security: user-guide/security.md
  - Developer Guide:
    - Development Setup: developer-guide/development-setup.md
    - Code Structure: developer-guide/code-structure.md
    - Adding Tools: developer-guide/adding-tools.md
    - Custom Policies: developer-guide/custom-policies.md
    - Testing: developer-guide/testing.md
  - Deployment:
    - Docker: deployment/docker.md
    - Kubernetes: deployment/kubernetes.md
    - Production: deployment/production.md
    - Monitoring: deployment/monitoring.md
  - Reference:
    - Configuration: reference/configuration.md
    - API Endpoints: reference/api-endpoints.md
    - Error Codes: reference/error-codes.md
    - Troubleshooting: reference/troubleshooting.md 