apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: metamcp-pdb
  namespace: metamcp
  labels:
    app: metamcp
    component: pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: metamcp
      component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: metamcp-admin-pdb
  namespace: metamcp
  labels:
    app: metamcp
    component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: metamcp
      component: admin