apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-file-pvc
  namespace: vault
  labels:
    app: vault
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-audit-pvc
  namespace: vault
  labels:
    app: vault
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard