name: Version Bump

on:
  workflow_dispatch:
    inputs:
      part:
        description: "Which part to bump"
        required: true
        default: "patch"
        type: choice
        options: [patch, minor, major]

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Bump version
        id: bump
        run: |
          python scripts/bump_version.py "${{ github.event.inputs.part }}"
          echo "version=$(python - <<'PY'
from metamcp import get_version
print(get_version())
PY
)" >> $GITHUB_OUTPUT

      - name: Create branch
        run: |
          branch="bump/release-${{ steps.bump.outputs.version }}"
          git checkout -b "$branch"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "chore(release): bump version to ${{ steps.bump.outputs.version }}"
          git push --set-upstream origin "$branch"

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "bump/release-${{ steps.bump.outputs.version }}"
          title: "chore(release): bump version to ${{ steps.bump.outputs.version }}"
          body: |
            Automated version bump to `${{ steps.bump.outputs.version }}`.
            - Updated `metamcp/__init__.py`, `pyproject.toml`, `k8s/deployment.yaml`, `docker-compose.yml`.
          labels: release
          draft: false

      - name: Output summary
        run: |
          echo "### Version bump PR created" >> $GITHUB_STEP_SUMMARY
          echo "- Version: ${{ steps.bump.outputs.version }}" >> $GITHUB_STEP_SUMMARY